### ISSUE TITLE
Add vscode-cdn.net to companies db

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/companiesdb#102]
_v--12s0ddraiu48ap5kmmvijle8b05dqgun6k938bhf2pqvs7l0lbka.vscode-cdn.net is a subdomain of vscode-cdn.net. DNS resolution of v--12s0ddraiu48ap5kmmvijle8b05dqgun6k938bhf2pqvs7l0lbka.vscode-cdn.net points to 13.107.237.69 with a location in Redmond, Washington US._

[whois data](https://domain.glass/v--12s0ddraiu48ap5kmmvijle8b05dqgun6k938bhf2pqvs7l0lbka.vscode-cdn.net)

Similar to #100 

<img width="363" alt="Screenshot 2023-02-18 at 7 01 28 am" src="https://user-images.githubusercontent.com/95468948/219792477-ebc9d7e0-6dc4-491d-9f1e-c433f3060dcd.png">

**Comment by jellizaveta** [comment]
https://github.com/AdguardTeam/companiesdb/commit/a1289b6d18a00190d45d4acc3bd09964c9888217
