### ISSUE TITLE
Add e-msedge.net to companies db

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/companiesdb#103]
_e-0014.e-msedge.net is a subdomain of e-msedge.net. DNS resolution of e-0014.e-msedge.net points to 13.107.5.93 with a location in Amsterdam, Noord-Holland NL. Parent domain registration belongs to Microsoft Corporation, registered through MarkMonitor, Inc.. The server responds with an SSL certificate issued by Microsoft Corporation to Microsoft Corporation under the common name *.azureedge.net.
The following endpoints are used to connect to the Microsoft 365 admin center's shared infrastructure, including Office in a browser. For more info, see Office 365 URLs and IP address ranges. You can turn this off by removing all Microsoft Office apps and the Mail and Calendar apps. If you turn off traffic for these endpoints, users won't be able to save documents to the cloud or see their recently used documents.
This hostname may be used by Microsoft products for the purposes of Used by Microsoft OfficeHub to get the metadata of Microsoft Office apps(HTTPS)._

[Whois data](https://domain.glass/e-0014.e-msedge.net)

<img width="153" alt="Screenshot 2023-02-18 at 7 06 14 am" src="https://user-images.githubusercontent.com/95468948/219793219-938b4212-79ef-4d89-ac03-ef49c3667096.png">

**Comment by jellizaveta** [comment]
closed via https://github.com/AdguardTeam/companiesdb/commit/a1289b6d18a00190d45d4acc3bd09964c9888217
