### ISSUE TITLE
Add exp-tas.com to companies db

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/companiesdb#104]
_default.exp-tas.com is a subdomain of exp-tas.com. DNS resolution of default.exp-tas.com points to 13.107.13.93 with a location in London, England US. Hosting or network services services are provided on Microsoft Corporation networks via Microsoft Azure. Parent domain registration belongs to Microsoft Corporation, registered through NOM-IQ Ltd dba Com Laude. The server responds with an SSL certificate issud by Microsoft Corporation to Microsoft Corporation under the common name *.exp-tas.com._

[whois data](https://domain.glass/default.exp-tas.com)

<img width="143" alt="Screenshot 2023-02-18 at 7 09 50 am" src="https://user-images.githubusercontent.com/95468948/219793810-2c69ddac-3cda-4d3d-90da-671a8a875161.png">

**Comment by jellizaveta** [comment]
closed via https://github.com/AdguardTeam/companiesdb/commit/a1289b6d18a00190d45d4acc3bd09964c9888217
