### ISSUE TITLE
[error] unpacking udp packet: dns: overflow unpacking uint16

### ISSUE THREAD

**Issue by dtouzeau** [AdguardTeam/companiesdb#11]
We have many error like 
`[error] unpacking udp packet: dns: overflow unpacking uint16`
what does it means ?

**Comment by ameshkov** [comment]
You're probably reporting this to a wrong repo.

From the error text it looks like you're running dnsproxy or AdGuard Home. Most likely there's some garbage UDP traffic incoming which is reported as this error. Tbh, it can safely been ignored.
