### ISSUE TITLE
Add office.com

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/companiesdb#119]
_syd-efz.ms-acdc.office.com is a subdomain of office.com. DNS resolution of syd-efz.ms-acdc.office.com points to 40.100.144.242 with a location in Sydney, New South Wales AU. Parent domain registration belongs to Microsoft Corporation, registered through MarkMonitor, Inc.. The server responds with an SSL certificate issud by Digicert Inc to Microsoft Corporation under the common name outlook.com._

[whois data](https://domain.glass/SYD-efz.ms-acdc.office.cOM)

<img width="201" alt="Screenshot 2023-02-18 at 8 19 37 am" src="https://user-images.githubusercontent.com/95468948/219804569-b6c5c506-8049-47b5-8da6-f4ed52a6762c.png">

**Comment by jellizaveta** [comment]
The domain is in the whotracks.me information
<details><summary>Screenshot:</summary>

<img width="477" alt="Screenshot 2023-02-20 at 19 48 49" src="https://user-images.githubusercontent.com/91964807/220172943-8ed444a2-3b66-44c7-bf76-d59da4c64899.png">

</details><br/>

**Comment by jslawler** [comment]
I'm not sure whether there had been an update after I raised this issue, but at the time there was no company data attached.

For some odd reason the last 2 letters of .cOM were uppercase. I'm not sure if there's an issue there or not, but something to be aware of.
