### ISSUE TITLE
Add netify.ai

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/companiesdb#121]
_static.netify.ai is a subdomain of netify.ai. DNS resolution of static.netify.ai points to 34.130.237.139 with a location in Houston, Texas US. Parent domain registration belongs to eGloo Inc., registered through 101domain._

[whois data](https://domain.glass/static.netify.ai)

[What is Netify?](https://www.netify.ai/products/netify-data-feeds) - @ameshkov, this could be pretty handy for AdGuard to cut down a lot of manual handling.

<img width="111" alt="Screenshot 2023-02-18 at 8 36 14 am" src="https://user-images.githubusercontent.com/95468948/219809376-4e0f9e6a-031c-459e-ac5e-2cbc353cb4ca.png">

**Comment by ameshkov** [comment]
Netify's cool, but you can't make their info public.
