### ISSUE TITLE
Add whatsabyte.com

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/companiesdb#124]
_DNS resolution of whatsabyte.com points to 100.21.184.71 with a location in Portland, Oregon US. The server responds with an SSL certificate issud by Let's Encrypt under the common name whatsabyte.com._
[Whois data](https://domain.glass/whatsabyte.com)

It's essentially a blog for reviewing IT tools.

**Comment by jellizaveta** [comment]
not a popular service

**Comment by jslawler** [comment]
If being a popular service is a requirement to be added to the database, it should possibly be added to the readme to prevent future issues.

We should also have a definition of what is to be a popular service if this is going to be the case going forward.
