### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/companiesdb#158]
Adapt our repository instruction from Notion.
There are two variants (need to be discussed):

* rework README.md
* remove contributing info and add new file `CONTRIBUTING.md` and link in `README.md` in `Contribute` section.

**Comment by jellizaveta** [comment]
There is not much information, so I think we can add data in README.md file as it is done in the AdGuard Home repository

**Comment by Alex-302** [comment]
Ok.
