### ISSUE TITLE
Add news aggregators to list of categories

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/companiesdb#16]
News aggregators are really too big to ignore and don't fit into the existing categories. We should avoid misc where possible for large amounts of common categories.

https://en.wikipedia.org/wiki/News_aggregator
https://en.wikipedia.org/wiki/Category:News_aggregators

This would allow us to add Apple News (#14 ) as well as many other news aggregators.

**Comment by ameshkov** [comment]
The logic behind current categories is the following: try to categorize ads and tracking and everything that's related to tracking at least somehow, and put everything else misc :)

It's hard to tie news aggregators with tracking apart from the fact that they're usually full of it themselves, but so are other websites on the internet.
