### ISSUE TITLE
Which company should be shown in a chain of companies

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/companiesdb#241]
In this [pr](https://github.com/AdguardTeam/companiesdb/pull/240) as an example, Soomla was acquired by ironSource, which is in turn owned by Unity.

In this example, we have ironSource listed as a company, with Soomla listed as a tracker for ironSource.
We also have Unity listed as a seperate company from ironSource.

As shown in the example above, we can see there's 3 tiers in the hierarchy of businesses, but maybe this should be defined better?

Using the example above, do we only list the highest company in the chain in the companies.json, and list all other companies listed in trackers.json, or should we list them another way?

**Comment by jellizaveta** [comment]
Company refers to the business who owns the tracker or the subsidiary company that produces the tracker. Since this database is based on third-party database some companies may not follow the same logic, but in most cases it does.
