### ISSUE TITLE
Add xtracloud.net to Qualcomm Incorporated companies data

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/companiesdb#25]
Whois data: https://who.is/whois/xtracloud.net

<img width="326" alt="Screenshot 2023-01-28 at 6 20 05 am" src="https://user-images.githubusercontent.com/95468948/215194983-6e2dda1e-23f7-4dea-bd11-117abd390eb3.png">

**Comment by jellizaveta** [comment]
@jslawler Hi! Where `xtracloud.net` is used?
