### ISSUE TITLE
Microsoft.com icon not showing correctly in AdGuard DNS

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/companiesdb#286]
**Expected**
<img width="209" alt="Screenshot 2023-10-17 at 5 48 45 pm" src="https://github.com/AdguardTeam/companiesdb/assets/95468948/dfdef419-5754-4657-8a2c-133ba530d3b9">

**Actual**
<img width="118" alt="Screenshot 2023-10-17 at 5 49 15 pm" src="https://github.com/AdguardTeam/companiesdb/assets/95468948/6ecd21c2-3a30-4483-82c5-b9d13ec691aa">

**Comment by jellizaveta** [comment]
Works fine on my end. 
<details><summary>Screenshot:</summary>

<img width="192" alt="Screenshot 2024-01-15 at 8 59 37 PM" src="https://github.com/AdguardTeam/companiesdb/assets/91964807/1249a39f-ee2d-4209-ba40-0de9f95c528a">

</details><br/>
