### ISSUE TITLE
Add solaredge.com to SolarEdge companies data

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/companiesdb#33]
whois data: https://domain.glass/SolarEdge.com

This is a company that develops solar equipment.

<img width="228" alt="Screenshot 2023-01-31 at 7 51 39 am" src="https://user-images.githubusercontent.com/95468948/215603394-348a9b63-fa2f-4b6c-8768-350674cf1a23.png">

**Comment by jellizaveta** [comment]
For what purpose is this domain used?

**Comment by jslawler** [comment]
That's the domain used by SolarEdge to send solar system performance data between inverters  and the cloud for remote monitoring.

It's used both by consumers and business.

Below is an example.

![image](https://user-images.githubusercontent.com/95468948/216375540-de6e38b1-7908-46cc-b4ad-bbf12cf718c5.png)
