### ISSUE TITLE
Add spotifycdn.com to Spotify 

### ISSUE THREAD

**Issue by Kutschel** [AdguardTeam/companiesdb#357]
### Describe the issue

Spotify uses and owns spotifycdn.com. URL is not in the company db for Spotify.
https://www.whois.com/whois/spotifycdn.com

### What is the name of the company?

Spotify

### What is the address of the company website?

spotify.com

### Add your comment and screenshots.

![image](https://github.com/AdguardTeam/companiesdb/assets/168834287/0e31b7c1-4c34-4384-a984-a032cd4067f4)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Thank you, added https://github.com/AdguardTeam/companiesdb/pull/359
