### ISSUE TITLE
favicon missing for akamai.com, but is present in the website source

### ISSUE THREAD

**Issue by emeritaacuity0u** [AdguardTeam/companiesdb#374]
AdGuard icon detection link shows a [grey image with an A](https://icons.adguard.org/icon?domain=akamai.com), however when viewing the source code for akamai.com, the[ favicon is definitely present.](https://www.akamai.com/site/favicon/favicon.ico)

**Comment by jellizaveta** [comment]
Duplicate https://github.com/AdguardTeam/companiesdb/issues/209
