### ISSUE TITLE
Add domain list for Adobe Firefly in AdGuard VPN exclusions

### ISSUE THREAD

**Issue by PavelParkhomenko** [AdguardTeam/companiesdb#392]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not a report to update the database.

### Problem description

Currently, adding only the domains "adobe.com" and "firefly.adobe.com" is insufficient to fully include all traffic related to Adobe Firefly in the VPN tunnel when using selective mode for exclusions in AdGuard VPN.

### Proposed solution

Add a domain list for Adobe Firefly so users can easily include all relevant domains in the VPN exclusion list with a single selection.

### Additional information

Adobe Firefly (https://firefly.adobe.com/) is a generative AI model that’s part of Adobe Creative Cloud, currently in open beta.

**Comment by Nexxef** [comment]
Здравствуйте! Хотел бы использовать Adobe Firefly. Я использую ВПН локально и хотелось бы получить необходимые домены, чтобы добавить их в исключения для своей корректной работы...

**Comment by jellizaveta** [comment]
Hello. Thank you for your contribution. Adobe domains have been added to VPN exclusions, updates will appear in the product within a day.
