### ISSUE TITLE
Add `githubcopilot.com` domain to GitHub

### ISSUE THREAD

**Issue by AlexandrPkhm** [AdguardTeam/companiesdb#401]
### Describe the issue

> As described in https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/779

### Issue Details

For GitHub Copilot to work, the domain `githubcopilot.com` and its subdomains must also be filtered, see https://docs.github.com/en/enterprise-cloud@latest/copilot/managing-copilot/managing-github-copilot-in-your-organization/configuring-your-proxy-server-or-firewall-for-copilot.

### Proposed solution

Add `githubcopilot.com` to the list of GitHub domains in `Exclusions > Add website > From the list > Work communication tools > GitHub`.

### What is the name of the company?

Github

### What is the address of the company website?

githubcopilot.com

### List the domains that are used by the tracker or service.

1. githubcopilot.com

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Thanks for contribution, added. Will be in VPN within a 24 h.
