### ISSUE TITLE
Add usertrust.com to companies database

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/companiesdb#42]
whois data: https://domain.glass/usertrust.com

usertrust.com is owned by Sectigo Limited and assumed to be the domain they use for SSL certificates. It likely falls under category 5, similar to pki.goog.

2 domains associated with usertrust.org are appearing in my query logs
ocsp.usertrust.com
crt.usertrust.com

<img width="159" alt="Screenshot 2023-02-03 at 4 48 02 pm" src="https://user-images.githubusercontent.com/95468948/216533366-32528415-27d1-40e3-bc2d-45b023628ac1.png">

**Comment by jellizaveta** [comment]
Closed vis https://github.com/AdguardTeam/companiesdb/pull/70
