### ISSUE TITLE
mradx.net - wrong company

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/companiesdb#6]
**Actual**: Magafon
**Correct**: Mail.ru
![image](https://user-images.githubusercontent.com/8361299/171884905-71ac66a0-47c6-41db-a0f8-d5f1458f1348.png)

**Comment by Mizzick** [comment]
https://github.com/AdguardTeam/companiesdb/blob/main/dist/whotracksme.json#L21595

@Alex-302, please check it again?

**Comment by Alex-302** [comment]
@Mizzick Same

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/172370748-0226fe67-2176-4eba-b2d7-70421031a633.png)


</details>

**Comment by Mizzick** [comment]
@atropnikov I guess it's on your side

**Comment by atropnikov** [comment]
@Mizzick companyId points to "megafon" https://github.com/AdguardTeam/companiesdb/blob/main/dist/whotracksme.json#L10508
