### ISSUE TITLE
Add publicassets.cdn-apple.com to Apple companies database

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/companiesdb#64]
whois data: https://domain.glass/publicassets.cdn-apple.com

I don't know what this is for, but it's coming from all devices on the network.

<img width="258" alt="Screenshot 2023-02-03 at 6 28 05 am" src="https://user-images.githubusercontent.com/95468948/217775084-6c9fd544-23b4-4ac5-af4e-d9245832cbcb.png">

**Comment by jellizaveta** [comment]
closed via https://github.com/AdguardTeam/companiesdb/pull/73
