### ISSUE TITLE
updates.cdn-apple.com

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/companiesdb#83]
_updates.cdn-apple.com is a subdomain of cdn-apple.com. DNS resolution of updates.cdn-apple.com points to 17.253.31.201 with a location in Seattle, Washington US. Network services are provided by Apple. Parent domain registration belongs to Apple Inc., registered through CSC Corporate Domains, Inc.. The server responds with an SSL certificate issud by Apple Inc., C to Apple Inc., St under the common name updates.cdn-apple.com, o._

[Whois data](https://domain.glass/updates.cdn-apple.com)

<img width="173" alt="Screenshot 2023-02-15 at 3 34 52 pm" src="https://user-images.githubusercontent.com/95468948/218941663-05053a99-ede5-44b0-b2cc-de88d7f3a294.png">

**Comment by jellizaveta** [comment]
hmmm `cdn-apple.com` - is on the list of domains related to apple.

**Comment by jslawler** [comment]
I just double checked, there's still no company data for it.

![image](https://user-images.githubusercontent.com/95468948/219145863-9e9a48ea-8a91-4815-90dd-aad87d7fbce5.png)

**Comment by jellizaveta** [comment]
Fixed, thanks for reporting it

<details><summary>Screenshot:</summary>

<img width="443" alt="Screenshot 2023-02-16 at 17 49 04" src="https://user-images.githubusercontent.com/91964807/219417122-d6645401-72f4-4b2a-b5f4-2d7a84e2a661.png">

</details><br/>
