### ISSUE TITLE
Add mdp-appconf-sg.heytapdl.com to companies db

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/companiesdb#89]
_mdp-appconf-sg.heytapdl.com is a subdomain of heytapdl.com. DNS resolution of mdp-appconf-sg.heytapdl.com points to 163.181.49.226 with a location in Madrid, Madrid, Comunidad de ES. The server responds with an SSL certificate issud by Digicert Inc to 深圳市欢太科技有限公司 under the common name nearme.com.cn._

[Whois data](https://domain.glass/mdp-appconf-sg.heytapdl.com)

<img width="235" alt="Screenshot 2023-02-16 at 9 01 48 am" src="https://user-images.githubusercontent.com/95468948/219253560-ef82eca2-6e3b-4b9c-b64f-8769d6ab675a.png">

**Comment by jslawler** [comment]
_mdp-appconf-oca.heytapdl.com.la_ doesn't resolve but it's quite obviously linked to the above.

<img width="255" alt="Screenshot 2023-02-16 at 9 01 54 am" src="https://user-images.githubusercontent.com/95468948/219253921-d0af5b5b-bd4e-468c-99a9-24d627ed5836.png">

**Comment by ameshkov** [comment]
.lan most likely is your search domain, it is not the same thing.

https://en.m.wikipedia.org/wiki/Search_domain

**Comment by jslawler** [comment]
> .lan most likely is your search domain, it is not the same thing.
> 
> https://en.m.wikipedia.org/wiki/Search_domain

Should this be raised under a seperate issue?

**Comment by ameshkov** [comment]
Not really, search domains can be customized and depend on you. We should probably just ignore it, one can't categorize every domain:)
