### ISSUE TITLE
Add ntp.org to companies db

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/companiesdb#96]
_DNS resolution of ntp.org points to 204.93.207.22 with a location in Chicago, Illinois US. Domain name registration belongs to Network Time Foundation, registered through Tucows, Inc.. The server responds with an SSL certificate issud by Let's Encrypt under the common name ntp.org._

[Whois data](https://domain.glass/ntp.org)

<img width="102" alt="Screenshot 2023-02-17 at 1 33 13 pm" src="https://user-images.githubusercontent.com/95468948/219542838-b76408de-2b98-4636-89a2-3fb362f7fc0e.png">

**Comment by jellizaveta** [comment]
For what purposes is this domain used?
